server:
  port: 8083

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/kokoo?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://127.0.0.1:3306/kokoo?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true
    username: kokoo
    password: kokoo0717
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true

devtools:
  livereload:
    enabled: true
